// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://phxoqxegjcqjmdszyipa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBoeG9xeGVnamNxam1kc3p5aXBhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMzAzOTksImV4cCI6MjA3MTcwNjM5OX0.VX8Xk4EEVv-V88sih6fwLSG53leP_rvnIprEQ4kFM9Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});